# Generated by Django 5.2.4 on 2025-08-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnCard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol_alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('pronunciation', models.CharField(max_length=250)),
            ],
        ),
    ]
