# Generated by Django 5.2.4 on 2025-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnCard', '0002_symbol_alphabet'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='word_image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/', verbose_name='Изображение'),
        ),
    ]
