# Generated by Django 5.2.4 on 2025-08-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnCard', '0003_words_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word_image',
            field=models.ImageField(blank=True, null=True, upload_to='words_images/', verbose_name='Изображение'),
        ),
    ]
